package com.github.alphapaca.reviewagent.service

import com.github.alphapaca.reviewagent.model.CreateReviewRequest
import com.github.alphapaca.reviewagent.model.PRInfo
import com.github.alphapaca.reviewagent.model.ReviewComment
import com.github.alphapaca.reviewagent.model.ReviewCommentRequest
import com.github.alphapaca.reviewagent.model.Severity
import io.ktor.client.HttpClient
import io.ktor.client.engine.cio.CIO
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.client.request.get
import io.ktor.client.request.header
import io.ktor.client.request.post
import io.ktor.client.request.setBody
import io.ktor.client.statement.bodyAsText
import io.ktor.http.ContentType
import io.ktor.http.contentType
import io.ktor.http.isSuccess
import io.ktor.serialization.kotlinx.json.json
import kotlinx.serialization.json.Json
import org.slf4j.LoggerFactory

class GitHubService(
    private val token: String,
    private val owner: String,
    private val repo: String
) {
    private val logger = LoggerFactory.getLogger(GitHubService::class.java)

    private val json = Json {
        ignoreUnknownKeys = true
        encodeDefaults = true
    }

    private val client = HttpClient(CIO) {
        install(ContentNegotiation) { json(json) }
        engine { requestTimeout = 60_000 }
    }

    /**
     * Post review comments to a PR using the Create Review API.
     * Uses single review with multiple comments for efficiency.
     */
    suspend fun postReviewComments(
        prNumber: Int,
        headSha: String,
        comments: List<ReviewComment>
    ): Boolean {
        if (comments.isEmpty()) {
            logger.info("No review comments to post")
            return true
        }

        val reviewRequest = CreateReviewRequest(
            commitId = headSha,
            event = "COMMENT",
            body = buildSummary(comments),
            comments = comments.map { comment ->
                ReviewCommentRequest(
                    path = comment.filePath,
                    line = comment.line,
                    side = "RIGHT",
                    body = formatCommentBody(comment)
                )
            }
        )

        val response = client.post(
            "https://api.github.com/repos/$owner/$repo/pulls/$prNumber/reviews"
        ) {
            header("Authorization", "Bearer $token")
            header("Accept", "application/vnd.github+json")
            header("X-GitHub-Api-Version", "2022-11-28")
            contentType(ContentType.Application.Json)
            setBody(reviewRequest)
        }

        if (!response.status.isSuccess()) {
            val errorBody = response.bodyAsText()
            logger.error("Failed to post review: ${response.status} - $errorBody")
            return false
        }

        logger.info("Posted ${comments.size} review comments to PR #$prNumber")
        return true
    }

    /**
     * Get PR info to retrieve latest commit SHA.
     */
    suspend fun getPRInfo(prNumber: Int): PRInfo? {
        val response = client.get(
            "https://api.github.com/repos/$owner/$repo/pulls/$prNumber"
        ) {
            header("Authorization", "Bearer $token")
            header("Accept", "application/vnd.github+json")
            header("X-GitHub-Api-Version", "2022-11-28")
        }

        if (!response.status.isSuccess()) {
            logger.error("Failed to get PR info: ${response.status}")
            return null
        }

        return json.decodeFromString<PRInfo>(response.bodyAsText())
    }

    private fun buildSummary(comments: List<ReviewComment>): String {
        val issueCount = comments.count { it.severity == Severity.ISSUE }
        val suggestionCount = comments.count { it.severity == Severity.SUGGESTION }
        val noteCount = comments.count { it.severity == Severity.NOTE }

        return buildString {
            appendLine("## AI Code Review Summary")
            appendLine()
            if (issueCount > 0) appendLine("- **Issues:** $issueCount")
            if (suggestionCount > 0) appendLine("- **Suggestions:** $suggestionCount")
            if (noteCount > 0) appendLine("- **Notes:** $noteCount")
            appendLine()
            appendLine("_Review generated by review-agent_")
        }
    }

    private fun formatCommentBody(comment: ReviewComment): String {
        val severityEmoji = when (comment.severity) {
            Severity.ISSUE -> ":warning:"
            Severity.SUGGESTION -> ":bulb:"
            Severity.NOTE -> ":information_source:"
        }
        return "$severityEmoji **${comment.severity.name}**: ${comment.body}"
    }

    fun close() {
        client.close()
    }
}
